server.address=127.0.0.1
server.port=8080

spring.application.name=next-dent-api

# 1. Credenciales de la Base de Datos (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/next_dent
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuracion de Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Mantenemos 'update' para que Hibernate cree las tablas automaticamente
spring.jpa.hibernate.ddl-auto=update

# 3. Mostrar el SQL en la consola (util para debugear)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
